{
 "title": "5G Slicing Monitoring Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Slice",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{namespace=~\"embb|urllc|massive-iot\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Core Usage per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Request Rate per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  rate(http_requests_total{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "1000 * (sum by (namespace) (\r\n  rate(http_request_duration_seconds_sum{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n) / sum by (namespace) (\r\n  rate(http_request_duration_seconds_count{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}