{
 "title": "5G Slicing Monitoring Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Slice",
    "query": {
     "query": "label_values({namespace=~\"embb|urllc|massive-iot|non-slice\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Core Usage per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[1m])) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Slice",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Request Rate per Slice",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(http_requests_total{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[60s])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Latency per Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum by (namespace) (\r\n  irate(http_request_duration_seconds_sum{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n) / sum by (namespace) (\r\n  irate(http_request_duration_seconds_count{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Round Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  rate(http_request_duration_seconds_sum{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[1m])\r\n)*10\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Latency over 5 minutes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  increase(http_request_duration_seconds_sum{namespace=~\"$namespace\", handler!=\"/metrics\", handler!=\"/health\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(http_requests_total{\r\n    namespace=~\"$namespace\",\r\n    handler=~\"/api/request|/authenticate\"\r\n  }[1m])\r\n)\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Session Establishment",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(http_requests_total{\r\n    namespace=~\"$namespace\",\r\n    handler=~\"/api/request|/start_session|/apply_policy|/allocate_resources\"\r\n  }[1m])\r\n)\r\n\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\n  irate(http_requests_total{\r\n    namespace=~\"$namespace\",\r\n    handler=~\"/api/request|/forward_data\"\r\n  }[1m])\r\n)\r\n\r\n",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Restarts",
   "type": "timeseries",
   "description": "Because of error",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by (namespace) (\r\nincrease(kube_pod_container_status_restarts_total{namespace=~\"embb|massive-iot|urllc|non-slice\"}[5m])\r\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}