apiVersion: batch/v1
kind: Job
metadata:
  name: ue-simulator
spec:
  template:
    spec:
      containers:
      - name: ue-simulator
        image: eliasandronikou/ue-simulator:latest  # Replace with your Docker image
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8000"  # URL of the API Gateway
      restartPolicy: Never
  backoffLimit: 4  # Number of retries in case of failure