apiVersion: batch/v1
kind: Job
metadata:
  name: ue-simulator
spec:
  template:
    spec:
      containers:
      - name: ue-simulator
        image: eliasandronikou/ue-simulator:latest 
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8000"
      restartPolicy: Never
  backoffLimit: 4  # Number of retries in case of failure