apiVersion: v1
kind: Namespace
metadata:
  name: embb
---
apiVersion: v1
kind: Namespace
metadata:
  name: massive-iot
---
apiVersion: v1
kind: Namespace
metadata:
  name: urllc
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-embb
  namespace: embb
spec:
  hard:
    cpu: "4"
    memory: "8Gi"
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-massive-iot
  namespace: massive-iot
spec:
  hard:
    cpu: "2"
    memory: "4Gi"
    pods: "50"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-urllc
  namespace: urllc
spec:
  hard:
    cpu: "4"
    memory: "8Gi"
    pods: "25"
