apiVersion: v1
kind: Namespace
metadata:
  name: embb
---
apiVersion: v1
kind: Namespace
metadata:
  name: massive-iot
---
apiVersion: v1
kind: Namespace
metadata:
  name: urllc
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-embb
  namespace: embb
spec:
  hard:
    cpu: "1.5"
    memory: "2.0Gi"
    pods: "10"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-massive-iot
  namespace: massive-iot
spec:
  hard:
    cpu: "1"
    memory: "1.0Gi"
    pods: "30"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-urllc
  namespace: urllc
spec:
  hard:
    cpu: "1.5"
    memory: "2.5Gi"
    pods: "15"
---
apiVersion: v1
kind: Namespace
metadata:
  name: non-slice
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-non-slice
  namespace: non-slice
spec:
  hard:
    cpu: "4"
    memory: "5.5Gi"
    pods: "55"
