apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: embb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: eliasandronikou/session-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        resources:
          requests:
            cpu: "300m"
            memory: "384Mi"
          limits:
            cpu: "600m"
            memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: embb
spec:
  selector:
    app: session-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: massive-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: eliasandronikou/session-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        resources:
          requests:
            cpu: "300m"
            memory: "384Mi"
          limits:
            cpu: "600m"
            memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: massive-iot
spec:
  selector:
    app: session-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: urllc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: eliasandronikou/session-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        resources:
          requests:
            cpu: "300m"
            memory: "384Mi"
          limits:
            cpu: "600m"
            memory: "768Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: urllc
spec:
  selector:
    app: session-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002