apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: non-slice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-service
  template:
    metadata:
      labels:
        app: session-service
    spec:
      containers:
      - name: session-service
        image: eliasandronikou/session-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        ports:
        - containerPort: 8002
        readinessProbe:
          httpGet:
            path: /health
            port: 8002
        livenessProbe:
          httpGet:
            path: /health
            port: 8002
        resources:
          requests:
            cpu: "400m" 
            memory: "750Mi" 
          limits:
            cpu: "600m"
            memory: "1000Mi" 
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: non-slice
  labels:
    app: session-service
spec:
  selector:
    app: session-service
  ports:
  - name: http
    protocol: TCP
    port: 8002
    targetPort: 8002