apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: eliasandronikou/data-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "2"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
spec:
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005