apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: embb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: eliasandronikou/data-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "embb"  # Slice type for eMBB
        resources:
          requests:
            cpu: "200m"
            memory: "192Mi"
          limits:
            cpu: "400m"
            memory: "384Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: embb
spec:
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: massive-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: eliasandronikou/data-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "massive-iot"  # Slice type for Massive IoT
        resources:
          requests:
            cpu: "200m"
            memory: "192Mi"
          limits:
            cpu: "400m"
            memory: "384Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: massive-iot
spec:
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  namespace: urllc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      containers:
      - name: data-service
        image: eliasandronikou/data-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "urllc"  # Slice type for URLLC
        resources:
          requests:
            cpu: "200m"
            memory: "192Mi"
          limits:
            cpu: "400m"
            memory: "384Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-service
  namespace: urllc
spec:
  selector:
    app: data-service
  ports:
  - protocol: TCP
    port: 8005
    targetPort: 8005