apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: embb-slice-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - embb
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: massive-iot-slice-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - massive-iot
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: urllc-slice-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - urllc