apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: non-slice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eliasandronikou/auth-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        resources:
          requests:
            cpu: "300m"
            memory: "400Mi"
          limits:
            cpu: "600m"
            memory: "800Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: non-slice
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001