apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: embb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eliasandronikou/auth-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "embb"
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        resources:
          requests:
            cpu: "120m"
            memory: "60Mi"
          limits:
            cpu: "300m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: embb
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: massive-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eliasandronikou/auth-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "massive-iot"
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        resources:
          requests:
            cpu: "80m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "80Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: massive-iot
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: urllc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: eliasandronikou/auth-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "urllc"
        ports:
        - containerPort: 8001
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
        resources:
          requests:
            cpu: "200m"
            memory: "120Mi"
          limits:
            cpu: "200m"
            memory: "120Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: urllc
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    protocol: TCP
    port: 8001
    targetPort: 8001