apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: your-policy-service-image:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        resources:
          requests:
            cpu: "400m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003