apiVersion: batch/v1
kind: Job
metadata:
  name: ue-simulator
spec:
  template:
    spec:
      containers:
      - name: ue-simulator
        image: eliasandronikou/ue-simulator:latest
        env:
        - name: API_GATEWAY_URL
          value: "http://api-gateway.non-slice.svc.cluster.local:8000"  # Correct URL for the API Gateway
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"
      restartPolicy: Never  # Ensures the job runs once and exits
  backoffLimit: 4  # Number of retries in case of failure