apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: embb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "embb"  # Slice type for eMBB
        ports:
        - containerPort: 8003
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
        resources:
          requests:
            cpu: "250m"
            memory: "150Mi"
          limits:
            cpu: "400m"
            memory: "250Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: embb
  labels:
    app: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: massive-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "massive-iot"  # Slice type for Massive IoT
        ports:
        - containerPort: 8003
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
        resources:
          requests:
            cpu: "130m"
            memory: "80Mi"
          limits:
            cpu: "200m"
            memory: "150Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: massive-iot
  labels:
    app: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: urllc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "urllc"  
        ports:
        - containerPort: 8003
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
        resources:
          requests:
            cpu: "200m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: urllc
  labels:
    app: policy-service
spec:
  selector:
    app: policy-service
  ports:
  - name: http
    protocol: TCP
    port: 8003
    targetPort: 8003