apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: embb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "embb"  # Slice type for eMBB
        resources:
          requests:
            cpu: "300m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: embb
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: massive-iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "massive-iot"  # Slice type for Massive IoT
        resources:
          requests:
            cpu: "150m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: massive-iot
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: policy-service
  namespace: urllc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: policy-service
  template:
    metadata:
      labels:
        app: policy-service
    spec:
      containers:
      - name: policy-service
        image: eliasandronikou/policy-service:latest
        env:
        - name: CPU_MULTIPLIER
          value: "1000"
        - name: RAM_MULTIPLIER
          value: "1000000"
        - name: SLICE_TYPE
          value: "urllc"  # Slice type for URLLC
        resources:
          requests:
            cpu: "400m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: policy-service
  namespace: urllc
spec:
  selector:
    app: policy-service
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003